# Generated by Django 5.2.5 on 2025-08-29 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('creditos', models.PositiveSmallIntegerField(default=1)),
                ('descripcion', models.TextField()),
                ('maestro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.maestro')),
            ],
        ),
    ]
